### PR TITLE
Set serialNumber when merging

### PR DESCRIPTION
**Pull request by candrews**
Fixes: https://github.com/CycloneDX/cyclonedx-cli/issues/272

### CODE REVIEW

**Comment by candrews** [comment]
If you could also add the `hacktoberfest-accepted` label to PR, and/or add the `hacktober` tag/topic to this project, I'd greatly appreciate it - and doing so would potentially drive attention this project too, which would be nice.

**Comment by coderpatros** [comment]
I'm wondering if this should be opt-in or perhaps have an opt-out option? Or maybe only set the serial number if one of the input BOMs has it set?

**Comment by candrews** [comment]
I don't see the advantage of opt in... The specification says it SHOULD be set... So I think that's what this tool should do.
> Every BOM generated SHOULD have a unique serial number

**Comment by coderpatros** [comment]
Merged and release process started. Thanks for the contribution @candrews

**Pull request merged**
